### ISSUE TITLE
Is it possible to turn this one into a conda package?

### ISSUE THREAD

**Issue by noamgot** [cubao/pybind11-rdp#2]
I'm not familiar with the process, and don't know how complicated it would be , but I'd like to use this one as a conda package. thanks!

**Comment by district10** [comment]
@noamgot this project is generated from <https://github.com/pybind/cmake_example>. It has a conda build CI [here](https://github.com/cubao/pybind11-rdp/blob/master/.github/workflows/conda.yml), so it's supposed to be a valid conda package.

But I haven't spend time on conda packaging (and [CI failed right now](https://github.com/cubao/pybind11-rdp/actions/runs/3256436074/jobs/5346918854)), so I'm not sure if it works.

I may fix this later. (no guarantee)

**Comment by noamgot** [comment]
I would be happy to hear if this becomes available as a conda package. thanks!

**Comment by district10** [comment]
I tried add to conda recipes month ago: https://github.com/conda-forge/staged-recipes/pull/20985

Give up for now.
